################## Redis 基础配置 #####################
spring:
  redis:
    # 数据库索引 （默认0-15个库）,选择使用 0 号库
    database:
      db1: 1
      db2: 2
      db3: 3
    # Redis 服务器地址
    host: 127.0.0.1
    # Redis 服务器端口
    port: 6379
    # Redis 服务器密码(默认为null)没有就不写
    password:
    # 连接超时时间 单位ms（毫秒）
    timeout: 3000
    ################## Redis 线程池设置 #####################
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0