DROP TABLE IF EXISTS USER;
CREATE TABLE `user` (
 `id` BIGINT ( 20 ) NOT NULL AUTO_INCREMENT COMMENT '主键',
 `name` VARCHAR ( 20 ) NOT NULL COMMENT '姓名',
 `age` INT ( 5 ) DEFAULT NULL COMMENT '年龄',
 PRIMARY KEY ( `id` )
) ENGINE = INNODB DEFAULT CHARSET = utf8mb4;