# ???oss??
aliyun:
  oss:
    # ????
    bucket-name:
    # Endpoint???????yourEndpoint??Bucket???????Endpoint????1???????Endpoint???https://oss-cn-hangzhou.aliyuncs.com?
    endpoint:
    # ?????AccessKey????API?????????????????????RAM????API???????????RAM?????RAM???
    # AccessKeyID
    access-key:
    # accessKeySecret
    key-secret:
    # ????????
    file-host:
    # Bucket ?? zjkjgw.oss-cn-guangzhou.aliyuncs.com???????https???/??????url????
    url-prefix: https://????-guangzhou.aliyuncs.com/